alerting:
  github:
    repository-url: "https://github.com/Cydnirn/lks-gatus-leantime"
    token: ""

endpoints:
  - name: Leantime
    url: "http://lks-leantime-alb-31797513.us-east-1.elb.amazonaws.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] <= 500"
    alerts:
      - type: github
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        description: "Server down :("
